#!/bin/bash

# immediately fail if an error occurs
set -e

export NAME=badges
export PUSH_TO_REPLICATED=true
export ZDT_DEPLOYMENT=true
export NO_VHOST=false
export GITHUB_TOKEN=${GITHUB_TOKEN:-$GH_TOKEN}

git clone https://${GITHUB_TOKEN}@github.com/neighbourhoodie/gk-deploy-scripts.git

./gk-deploy-scripts/deploy
